import { test, expect } from "./mock-pi-fixture";
import { makeSeedProject } from "./open-session";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, readdirSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const workspace = makeSeedProject("BiosHistorySynthetic");
const root = join(mkdtempSync(join(tmpdir(), "pideck-seed-history-")), "knowledge");
execFileSync(process.execPath, [join(__dirname, "biosOnboardingSeed.mjs"), root]);
const git = (...args: string[]) => execFileSync("git", args, { cwd: workspace.path, encoding: "utf8", windowsHide: true });
git("init");
git("config", "user.name", "Synthetic");
git("config", "user.email", "synthetic@example.invalid");
writeFileSync(join(workspace.path, "Board.c"), "initial\n");
git("add", ".");
git("commit", "-m", "Initial CRB");
writeFileSync(join(workspace.path, "Board.c"), "fixed\n");
git("add", ".");
git("commit", "-m", "Fix synthetic S3 resume");
test.use({ seedProjects: [workspace], mockSessionInProject: true, seedSettings: { biosHost: { knowledgeRoot: root, authorizedProjectIds: [], authorizedRoots: [], endpoint: "unknown" } } });

test("HX GUI: auto-match → empty continuation → bounded Git → policy → AI candidate → human draft", async ({ window }, testInfo) => {
	test.setTimeout(180_000);
	const errors: string[] = [];
	window.on("pageerror", (error) => errors.push(error.message));
	await expect(window.locator("#boot-overlay")).toHaveCount(0, { timeout: 20_000 });
	await window.getByRole("tab", { name: "项目", exact: true }).click();
	const project = window.locator(".conversation", { hasText: workspace.name }).first();
	await project.click();
	const onboarding = window.getByTestId("bios-first-run");
	await onboarding.getByTestId("bios-first-run-consent").click();
	await onboarding.getByRole("button", { name: "确认授权并接入", exact: true }).click();
	await expect(onboarding).toContainText("项目已接入", { timeout: 25_000 });
	await onboarding.getByRole("button", { name: "关闭", exact: true }).click();
	await project.hover();
	await project.getByRole("button", { name: "普通会话", exact: true }).first().click();
	const composer = window.locator(".composer .rich-input");
	await expect(composer).toHaveAttribute("contenteditable", "true", { timeout: 30_000 });
	await composer.fill("History smoke");
	await composer.press("Enter");
	await expect(window.locator(".message-timeline")).toContainText("Mock 回复：「History smoke」", { timeout: 30_000 });
	if (await onboarding.isVisible()) await onboarding.getByRole("button", { name: "取消接入", exact: true }).click();
	const sessionId = await window.locator(".composer").getAttribute("data-session-id");
	if (!sessionId) throw new Error("Current composer session missing");
	await window.locator(".header-drawer-toggle").first().click();
	await window.getByTestId("drawer-rail-bios").click();
	await window.getByTestId("bios-manage-open").click();
	const wb = window.getByTestId("bios-management-dialog");
	const closeManager = () => wb.getByRole("button", { name: "Close", exact: true }).click();
	const reopenManager = () => window.getByTestId("bios-manage-open").click();
	await expect.poll(() => window.evaluate(async (id) => (await window.piDesktop.sessions.listRuntimes()).find((entry) => entry.sessionId === id)?.status, sessionId)).toBe("idle");
	await wb.getByRole("button", { name: "刷新", exact: true }).first().click();
	await wb.getByTestId("bios-workbench-section-tasks").click();
	await expect(wb.getByRole("combobox", { name: "项目", exact: true })).toContainText(workspace.name);
	await wb.getByRole("button", { name: "换对话接续", exact: true }).click();
	await expect(wb).toContainText("左侧聊天不是任务记录");
	await wb.getByRole("button", { name: "创建一个 BIOS 任务", exact: true }).click();
	await expect(wb).toContainText("新建任务");
	await wb.getByTestId("bios-workbench-section-knowledge").click();
	// CW：离开新建草稿也要显式放弃，不再静默丢弃。
	await window.getByRole("alertdialog").getByRole("button", { name: "丢弃并继续", exact: true }).click();
	await wb.getByRole("button", { name: "历史提炼", exact: true }).click();
	const history = window.getByTestId("bios-history");
	await expect(history.getByRole("textbox", { name: "分支 / Tag / 提交（默认 HEAD）" })).toHaveValue("HEAD");
	await history.getByRole("spinbutton").fill("1");
	await history.getByRole("button", { name: "读取本地提交", exact: true }).click();
	await expect(history).toContainText("本次检查 1 条提交，匹配 1 条");
	await expect(history).toContainText("还有更早提交未检查");
	await history.getByRole("button", { name: /Fix synthetic S3 resume/ }).click();
	await history.locator("summary").click();
	await expect(history.locator("pre")).toContainText("+fixed");
	await history.getByRole("button", { name: "准备 AI 经验分析", exact: true }).click();
	await expect(history).toContainText("端点策略尚未允许");
	await expect(composer).toHaveText("");
	await window.screenshot({ path: testInfo.outputPath("history-local-policy.png") });
	// Isolated trusted settings only. Real user's profile and knowledge remain untouched.
	await window.evaluate(() => window.piDesktop.bios.updateSettings({ endpoint: "allowed" }));
	await expect(history.getByRole("button", { name: /Fix synthetic/ })).toHaveCount(0);
	await closeManager();
	await window.evaluate((id) => window.piDesktop.sessions.activateRuntime(id), sessionId);
	await composer.fill("History reopened");
	await composer.press("Enter");
	await expect(window.locator(".message-timeline")).toContainText("Mock 回复：「History reopened」", { timeout: 30_000 });
	await expect.poll(() => window.evaluate(async (id) => (await window.piDesktop.sessions.listRuntimes()).find((entry) => entry.sessionId === id)?.status, sessionId)).toBe("idle");
	await reopenManager();
	await history.getByRole("button", { name: "读取本地提交", exact: true }).click();
	await history.getByRole("button", { name: /Fix synthetic S3 resume/ }).click();
	await closeManager();
	await composer.fill("Keep my draft");
	await reopenManager();
	await history.getByRole("button", { name: "准备 AI 经验分析", exact: true }).click();
	await expect(history).toContainText("未覆盖");
	await expect(composer).toHaveText("Keep my draft");
	await closeManager();
	await composer.press("ControlOrMeta+a");
	await composer.press("Backspace");
	await reopenManager();
	await history.getByRole("button", { name: "准备 AI 经验分析", exact: true }).click();
	await expect(composer).toContainText('"metadata":');
	await expect(history).toContainText("点击发送");
	expect(readdirSync(join(root, "experiences"))).toHaveLength(0);
	await closeManager();
	await expect(composer).toContainText('"metadata":');
	await window.locator(".composer-send-primary").click();
	await expect(window.locator(".message-timeline")).toContainText("Synthetic S3 resume failure", { timeout: 30_000 });
	// Import waits for a complete idle response, not a streaming prefix.
	await expect.poll(() => window.evaluate(async (id) => (await window.piDesktop.sessions.listRuntimes()).find((entry) => entry.sessionId === id)?.status, sessionId)).toBe("idle");
	await reopenManager();
	await history.getByRole("button", { name: "导入当前会话 AI 候选", exact: true }).click();
	await expect(history.getByRole("textbox", { name: "问题", exact: true })).toHaveValue("Synthetic S3 resume failure");
	await expect(history.getByRole("textbox", { name: "根因", exact: true })).toHaveValue("");
	await wb.getByTestId("bios-workbench-section-tasks").click();
	await expect(window.getByRole("alertdialog")).toBeVisible();
	await window.getByRole("alertdialog").getByRole("button", { name: "取消", exact: true }).click();
	await expect(history.getByRole("textbox", { name: "问题", exact: true })).toHaveValue("Synthetic S3 resume failure");
	await history.getByRole("textbox", { name: "问题", exact: true }).scrollIntoViewIfNeeded();
	await window.screenshot({ path: testInfo.outputPath("history-ai-candidate.png") });
	expect(readdirSync(join(root, "experiences"))).toHaveLength(0);
	await history.getByRole("button", { name: "创建草稿", exact: true }).click();
	await expect(history).toContainText("rootCause");
	expect(readdirSync(join(root, "experiences"))).toHaveLength(0);
	await history.getByRole("textbox", { name: "根因", exact: true }).fill("Engineer confirmed synthetic cause");
	const sourceField = history.getByRole("textbox", { name: "来源项目", exact: true });
	const sourceId = await sourceField.inputValue();
	await sourceField.fill("foreign-project");
	await history.getByRole("button", { name: "创建草稿", exact: true }).click();
	await expect(history).toContainText("来源项目或提交证据被修改");
	expect(readdirSync(join(root, "experiences"))).toHaveLength(0);
	await sourceField.fill(sourceId);
	await history.getByRole("button", { name: "创建草稿", exact: true }).click();
	await expect(history).toHaveCount(0);
	await expect(wb).toContainText("Synthetic S3 resume failure");
	await expect(wb).toContainText("人工审核");
	const files = readdirSync(join(root, "experiences"));
	expect(files).toHaveLength(1);
	const card = JSON.parse(await readFile(join(root, "experiences", files[0]), "utf8"));
	expect(card.status).toBe("draft");
	expect(card.validations).toEqual([]);
	expect(card.reuseScope.level).toBe("current-project");
	expect(card.evidence[0].commit).toBe(git("rev-parse", "HEAD").trim());
	await window.screenshot({ path: testInfo.outputPath("history-saved-draft.png") });
	// New prepared source draft is withdrawn on revocation, without deleting the saved card.
	await wb.getByRole("button", { name: "历史提炼", exact: true }).click();
	await history.getByRole("button", { name: "读取本地提交", exact: true }).click();
	await history.getByRole("button", { name: /Fix synthetic S3 resume/ }).click();
	await history.getByRole("button", { name: "准备 AI 经验分析", exact: true }).click();
	await expect(composer).toContainText('"metadata":');
	await window.evaluate(() => window.piDesktop.bios.updateSettings({ endpoint: "denied" }));
	await expect(composer).toHaveText("");
	await expect(history.getByRole("button", { name: /Fix synthetic/ })).toHaveCount(0);
	expect(readdirSync(join(root, "experiences"))).toHaveLength(1);
	await closeManager();
	await window.getByRole("button", { name: /^主题：/ }).click();
	await expect(window.locator("html")).toHaveAttribute("data-theme", "dark");
	await window.screenshot({ path: testInfo.outputPath("history-revoked-dark.png") });
	expect(git("diff", "--", "Board.c")).toBe("");
	expect(errors).toEqual([]);
});
