import { test, expect } from "./mock-pi-fixture";
import { makeSeedProject } from "./open-session";
import { execFileSync } from "node:child_process";
import { mkdtempSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const workspace = makeSeedProject("BiosOnboardingSynthetic");
const root = join(mkdtempSync(join(tmpdir(), "pideck-seed-onboarding-")), "knowledge");
execFileSync(process.execPath, [join(__dirname, "biosOnboardingSeed.mjs"), root]);
test.use({ seedProjects: [workspace], seedSettings: { biosHost: { knowledgeRoot: root, authorizedProjectIds: [], authorizedRoots: [], approvedCustomers: [], allowedFeatureIds: [], endpoint: "unknown" } } });

test("UI-MIN GUI: one prefilled onboarding modal → cancel → explicit authorization → no repeated form", async ({ window }, testInfo) => {
	test.setTimeout(120_000);
	const errors: string[] = [];
	window.on("pageerror", (error) => errors.push(error.message));
	await expect(window.locator("#boot-overlay")).toHaveCount(0, { timeout: 20_000 });
	await window.getByRole("tab", { name: "项目", exact: true }).click();
	const project = window.locator(".conversation", { hasText: workspace.name }).first();
	await project.click();
	const onboarding = window.getByTestId("bios-first-run");
	await expect(onboarding.getByRole("textbox", { name: "项目名称", exact: true })).toHaveValue(workspace.name);
	await expect(onboarding).toContainText(workspace.path);
	await expect(onboarding.getByTestId("bios-first-run-consent")).not.toBeChecked();
	await expect(onboarding.getByRole("button", { name: "确认授权并接入", exact: true })).toBeDisabled();
	await expect(window.getByRole("textbox", { name: "BIOS 项目 ID", exact: true })).toHaveCount(0);
	await onboarding.getByRole("button", { name: "取消接入", exact: true }).click();
	expect((await window.evaluate(() => window.piDesktop.bios.getSettings())).authorizedProjectIds).toEqual([]);
	expect(JSON.parse(await readFile(join(root, "registry.json"), "utf8")).projects).toEqual([]);
	await window.locator(".header-drawer-toggle").first().click();
	await window.getByTestId("drawer-rail-bios").click();
	await window.getByTestId("bios-onboarding-open").click();
	await onboarding.getByRole("textbox", { name: "项目名称", exact: true }).fill("My Synthetic Board");
	await onboarding.getByTestId("bios-first-run-consent").click();
	await onboarding.getByRole("button", { name: "确认授权并接入", exact: true }).click();
	await expect(onboarding).toContainText("项目已接入", { timeout: 25_000 });
	const registry = JSON.parse(await readFile(join(root, "registry.json"), "utf8"));
	expect(registry.projects).toHaveLength(1);
	const id: string = registry.projects[0].biosProjectId;
	expect(id).toMatch(/^[a-f0-9-]{36}$/);
	expect(registry.projects[0].displayName).toBe("My Synthetic Board");
	const settings = await window.evaluate(() => window.piDesktop.bios.getSettings());
	expect(settings.authorizedProjectIds).toEqual([id]);
	expect(settings.authorizedRoots).toEqual([workspace.path]);
	expect(settings.endpoint).toBe("unknown");
	expect(settings.approvedCustomers).toEqual([]);
	expect(settings.allowedFeatureIds).toEqual([]);
	await onboarding.getByRole("button", { name: "关闭", exact: true }).click();
	await expect(window.getByTestId("bios-onboarding-open")).toHaveCount(0);
	await window.getByTestId("bios-manage-open").click();
	await expect(window.getByTestId("bios-management-dialog")).toBeVisible();
	await expect(window.getByTestId("bios-onboarding")).toHaveCount(0);
	await expect(onboarding).toHaveCount(0);
	expect(JSON.parse(await readFile(join(root, "registry.json"), "utf8")).projects).toHaveLength(1);
	await window.keyboard.press("Escape");
	await window.getByRole("button", { name: /^设置/ }).click();
	const modal = window.locator(".settings-modal");
	await modal.getByText("BIOS 知识库", { exact: true }).click();
	await expect(modal.getByRole("combobox", { name: "模型端点策略" })).toContainText("尚未确认");
	await expect(modal.getByRole("textbox", { name: /授权项目 ID/ })).not.toBeVisible();
	await modal.locator("summary", { hasText: "高级：管理项目、需求、客户和目录授权" }).click();
	await expect(modal.getByRole("textbox", { name: /授权项目 ID/ })).toHaveValue(id);
	await window.keyboard.press("Escape");
	await window.getByRole("button", { name: /^主题：/ }).click();
	await expect(window.locator("html")).toHaveAttribute("data-theme", "dark");
	await expect(window.getByTestId("bios-compact-status")).toBeVisible();
	await window.screenshot({ path: testInfo.outputPath("minimal-onboarding-dark.png") });
	expect(errors).toEqual([]);
});
